### ISSUE TITLE
Problem with Installer 2023-06

### ISSUE THREAD

**Issue by hannibalstgt** [eclipse-oomph/oomph#20]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.29.0+Build+5945).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
[2023-08-21 14:56:51] Executing bootstrap tasks
[2023-08-21 14:56:51] OpenJDK Runtime Environment 17.0.7+7
[2023-08-21 14:56:51] Product org.eclipse.products.epp.package.java.**2023-06**
[2023-08-21 14:56:51] Bundle org.eclipse.oomph.setup 1.26.0.v20230416-0656, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
[2023-08-21 14:56:51] Bundle org.eclipse.oomph.setup.core 1.27.0.v20230402-0730, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
[2023-08-21 14:56:51] Bundle org.eclipse.oomph.setup.p2 1.19.0.v20230416-1150, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
[2023-08-21 14:56:51] Performing P2 Director (Eclipse IDE for Java Developers (2023-06) + JRE 17.0.8)
[2023-08-21 14:56:51] Offline = false
[2023-08-21 14:56:51] Mirrors = true
[2023-08-21 14:56:51] Resolving 27 requirements from 4 repositories to D:\java-2023-06\eclipse
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.justj.openjdk.hotspot.jre.full.feature.group (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux))(&(osgi.arch=aarch64)(osgi.os=macosx))(&(osgi.arch=ppc64le)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=macosx))(&(osgi.arch=x86_64)(osgi.os=win32))))
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:epp.package.java [4.28.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.28.0,5.0.0)
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.28.0,5.0.0)
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.buildship.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.eclemma.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.epp.mpc.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.bcoview.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jgit.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.logback.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.commons.activity.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.egit.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.git.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.github.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.hudson.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.ide_feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.java_feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.reviews.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext_feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tips.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tm.terminal.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.xml.feature.feature.group
[2023-08-21 14:56:51] Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
[2023-08-21 14:56:51] Repository https://download.eclipse.org/justj/jres/17/updates/release/latest
[2023-08-21 14:56:51] Repository https://download.eclipse.org/technology/epp/packages/2023-06/202306081200
[2023-08-21 14:56:51] Repository https://download.eclipse.org/releases/2023-06/202306141000
[2023-08-21 14:56:51] Repository https://download.eclipse.org/oomph/updates/milestone/latest
[2023-08-21 14:56:52] Calculating requirements and dependencies.
[2023-08-21 14:56:52] Computing prerequisite plan
[2023-08-21 14:56:53] Collecting 2 artifacts from https://download.eclipse.org/releases/2023-06/202306141000
[2023-08-21 14:56:55] Downloading org.eclipse.platform_root
[2023-08-21 14:56:55] Downloading org.eclipse.rcp_root
[2023-08-21 14:56:55] Collected 2 artifacts for https://download.eclipse.org/releases/2023-06/202306141000 in 1.473s
[2023-08-21 14:56:55] Collecting 1 artifacts from https://download.eclipse.org/technology/epp/packages/2023-06/202306081200
[2023-08-21 14:56:55] Downloading epp.package.java.executable.win32.win32.x86_64
[2023-08-21 14:56:55] Collected 1 artifacts for https://download.eclipse.org/technology/epp/packages/2023-06/202306081200 in 0s
[2023-08-21 14:56:55] An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
[2023-08-21 14:56:55] ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:578)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:359)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3792)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1353)
  at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage$20.run(SimpleVariablePage.java:1165)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=D__java-2023-06_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
  ERROR: org.eclipse.equinox.p2.engine code=0 Error reading signed content.
  java.io.FileNotFoundException: C:\Users\User\.p2\pool\plugins\org.eclipse.equinox.simpleconfigurator_1.4.200.v20221111-1340.jar (Das System kann die angegebene Datei nicht finden)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(Unknown Source)
    at java.base/java.io.FileInputStream.<init>(Unknown Source)
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.lambda$2(SignedContentFromBundleFile.java:198)
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.getSignedEntries(SignedContentFromBundleFile.java:223)
    at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.<init>(SignedContentFromBundleFile.java:193)
    at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent(SignedBundleHook.java:169)
    at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:173)
    at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:121)
    at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:64)
    at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
    at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
    at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
Message:       at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
    at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:48)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:574)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:359)
    at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3792)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
    at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1353)
    at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage$20.run(SimpleVariablePage.java:1165)

[2023-08-21 14:56:55] 
Message in red bar: Instalölation Show log      (presented log is above !)

![grafik](https://github.com/eclipse-oomph/oomph/assets/20060004/06efe5a4-4043-42c4-87a0-3121f404ba2a)

![grafik](https://github.com/eclipse-oomph/oomph/assets/20060004/29c1a555-8613-4627-9c92-9233d1636a82)
```

**Comment by hannibalstgt** [comment]
I have trried a lot of things but I cannot install Eclipse on Windows 11 64 Bit

**Comment by merks** [comment]
It's complain about this file not existing:
```
C:\Users\User\.p2\pool\plugins\org.eclipse.equinox.simpleconfigurator_1.4.200.v20221111-1340.jar 
```
I assume that file really does not exist, correct?

Unfortunately Windows anti-virus can block files being moved/renamed leading to problems like this one.  If a second attempt to installs fails in this same way, then you need to try to repair the bundle pool to fix this missing/broken artifact as described here:

https://www.eclipse.org/setups/installer/question/

Specifically the latest sentence here is relevant:

> Use the eclipse installer's Bundle Pools... menu item to manage where this pool is physically located on disk; this location can become large. The Bundle Pool Management dialog supports garbage collecting of unused artifacts, i.e., if you delete an installation, the artifacts it uses can potentially be removed from disk. In addition, if some artifact becomes corrupted, or if a corrupted artifact is downloaded from some mirror site, this dialog can be used to detect the damage and to repair it. 

Please let me know how that works out!

**Comment by merks** [comment]
There is no further action I can take.
