### ISSUE TITLE
setups.zip not being updated since Aug 16

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-oomph/oomph#21]
The [setups-archiver](https://ci.eclipse.org/oomph/job/setup-archiver/) job seems to have failed consistently since 16 Aug with git error messages:

```sh
 > git fetch --tags --force --progress -- https://github.com/eclipse-oomph/oomph.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/eclipse-oomph/oomph.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1003)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1245)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1309)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:159)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:70)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:312)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/eclipse-oomph/oomph.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: .git/index: index file smaller than expected

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2732)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2109)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:623)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1001)
	... 8 more
```

FWIW Those git commands work if I try it on my machine.

**Comment by merks** [comment]
I reconfigured it to use lightweight checkout and the build I kicked off worked:

https://ci.eclipse.org/oomph/job/setup-archiver/60846/

The above shows the changes that were promoted, which fortunately weren't so many!

I'll consider to send emails for failures again; in this past this build failed several times per day and the emails were super annoying...

**Comment by merks** [comment]
Oh wait, I did get an email that it's good 

![image](https://github.com/eclipse-oomph/oomph/assets/208716/2eee2027-147b-480e-819b-ff0b30617d05)

So I must have missed the email that it was bad...
