### ISSUE TITLE
Error debugging: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by pepcim** [eclipse-oomph/oomph#26]
Hello,
I installed Version: 2023-09 (4.29.0) // Build id: 20230907-1323

And I getting the following error each time I try to debug (normal executing works fine):

java.lang.UnsupportedClassVersionError: org/eclipse/jdt/launching/internal/javaagent/Premain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "main"

**Comment by merks** [comment]
That's not a problem Oomph can fix.  Please report the problem here:

https://github.com/eclipse-jdt/eclipse.jdt.debug/issues

I think you are trying to debug launch on a really old JVM.  Please include details about the JRE you are using when you open a JDT issue.
