### ISSUE TITLE
AgentImpl: can't OOmph platform due to NPE

### ISSUE THREAD

**Issue by jukzi** [eclipse-oomph/oomph#4]
I tried to OOmph https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md
(no p2 cache, Java 20)
but even after 5 retries it is stuck in exception:

```
Creating new baseline from target Modular API Baseline Target
org.eclipse.oomph.util.ReflectUtil$ReflectionException: org.eclipse.core.runtime.CoreException: Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:134)
  at org.eclipse.oomph.setup.pde.impl.APIBaselineFromTargetTaskImpl.perform(APIBaselineFromTargetTaskImpl.java:320)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.pde.api.tools.internal.model.ApiModelFactory.newApiBaselineFromTarget(ApiModelFactory.java:313)
  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.base/java.lang.reflect.Method.invoke(Method.java:578)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.setup.pde.impl.APIBaselineFromTargetTaskImpl.perform(APIBaselineFromTargetTaskImpl.java:320)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  ... 1 more
  ERROR: org.eclipse.oomph.targlets.core code=0 Cannot invoke "org.eclipse.equinox.p2.core.IProvisioningAgentProvider.createAgent(java.net.URI)" because "provider" is null
  Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.equinox.p2.core.IProvisioningAgentProvider.createAgent(java.net.URI)" because "provider" is null
    at org.eclipse.oomph.p2.internal.core.AgentImpl.getOrCreateProvisioningAgent(AgentImpl.java:1311)
    at org.eclipse.oomph.p2.internal.core.AgentImpl.getProvisioningAgent(AgentImpl.java:695)
    at org.eclipse.oomph.p2.internal.core.AgentImpl.getProfile(AgentImpl.java:423)
    at org.eclipse.oomph.p2.internal.core.BundlePoolImpl.getProfile(BundlePoolImpl.java:173)
    at org.eclipse.oomph.targlets.internal.core.TargletContainerDescriptor.getOrCreateProfile(TargletContainerDescriptor.java:368)
    at org.eclipse.oomph.targlets.internal.core.TargletContainerDescriptor.startUpdateTransaction(TargletContainerDescriptor.java:282)
    at org.eclipse.oomph.targlets.internal.core.TargletContainer.updateProfile(TargletContainer.java:955)
    at org.eclipse.oomph.targlets.internal.core.TargletContainer.resolveUnits(TargletContainer.java:649)
    at org.eclipse.oomph.targlets.internal.core.TargletContainer.resolveBundles(TargletContainer.java:597)
    at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:97)
    at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:431)
    at org.eclipse.pde.api.tools.internal.model.ApiModelFactory.newApiBaselineFromTarget(ApiModelFactory.java:311)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:578)
    at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
    at org.eclipse.oomph.setup.pde.impl.APIBaselineFromTargetTaskImpl.perform(APIBaselineFromTargetTaskImpl.java:320)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2382)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2407)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
    at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
    ... 1 more

Took 0 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

```

![image](https://github.com/eclipse-oomph/oomph/assets/51790620/b9d84755-ce22-4f38-a17e-ebbfe928bc59)

**Comment by merks** [comment]
I have a feeling this is caused by changes in p2 core's Activator that required changes here:

https://github.com/eclipse-oomph/oomph/blame/83e93b0dfd53cff61eb77694df731edfa10314b7/plugins/org.eclipse.oomph.p2.core/src/org/eclipse/oomph/p2/internal/core/ProvisioningAgentProvider.java#L42

Can you try it with a "nightly" installer?

https://download.eclipse.org/justj/?file=oomph/products/latest

I should probably change the configuration to specify using Oomph's nightly builds explicitly if that works...

**Comment by jukzi** [comment]
i will try

**Comment by jukzi** [comment]
Did work with nightly.

**Comment by merks** [comment]
So it's as I suspected. Safest for the future will be to explicitly specify Oomph's nightly build repo since we know we are installing an SDK I-Build that make have things that break and older Oomph.  Hopefully not too often.  😢 

I'll try to get to this sooner rather than later.  Still migrating Oomph right now...

**Comment by merks** [comment]
Given this problem affects **everyone** installing an an I-build version of the  Eclipse SDK, I fixed this in the catalog and in catalog generator.  Cool that the Oomph commit is cross linked back to this issue. 🆒 

Thanks for reporting the issue and for testing the nightly build installer!  😁
