### ISSUE TITLE
"The artifact is already available in the repository "

### ISSUE THREAD

**Issue by jukzi** [eclipse-oomph/oomph#58]
I was not able to OOmph Platform workspace today on first try. I do not understand the error message:
The error message gone when i retried using "back" and "finish"

```
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2448)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2473)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
    ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=C__Users_jkubitz_platform-2024-01-10_ws-36f24858156517d7b240931401b63cd369740d13, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    ERROR: org.eclipse.equinox.p2.artifact.repository code=1201 The artifact is already available in the repository file:/C:/Users/jkubitz/.p2/pool/.

Took 645 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

```
![image](https://github.com/eclipse-oomph/oomph/assets/51790620/e51590ca-99e8-4e77-aa21-cff9413afa9a)

**Comment by merks** [comment]
Yes, this happens occasionally with no known way to reproduce the problem unfortunately.  I don't even have a good theory for how the artifact got into the pool while at the same time the p2 seems to think it needs to download the artifact because it's not yet in the pool.  Perhaps something put the artifact into the pool folder but failed to update the artifact metadata to reflect that fact.

**Comment by jukzi** [comment]
related question: why is the pool used at all? I disabled it:
![image](https://github.com/eclipse-oomph/oomph/assets/51790620/6cf4afa9-43ae-4ed5-8afd-4419258e306e)

**Comment by merks** [comment]
There's always a pool, even if not a shared one.   That setting disables it for the p2 director task, i.e., so that the p2 direct creates an installation where its pool is colocated with (nested in) the installation.  This has no affect on targlets.

**Comment by merks** [comment]
This comment where the exception is thrown suggests to me there is some type of design problem in p2 in that two descriptors might be considered not equals (depending on the location properties) whereas a new one that's created from the other one might then be consider equals.

<img width="987" height="257" alt="Image" src="https://github.com/user-attachments/assets/84409b4a-268d-455e-93da-a1ba82441167" />

- org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactDescriptor.equals(Object)
- org.eclipse.equinox.p2.repository.artifact.spi.ArtifactDescriptor.equals(Object)

I notice too, in the following case later, it will even overwrite the artifact:

<img width="920" height="151" alt="Image" src="https://github.com/user-attachments/assets/d84627c6-e0df-4764-91c4-ed1488ea8b87" />

I think the comment is maybe outdated because contains also creates a new descriptor:

<img width="687" height="135" alt="Image" src="https://github.com/user-attachments/assets/e884c39b-3c85-4ac2-b13f-07c685f2ea8e" />

So I don't really understand the overall design here and have no good theory for how the problem arises.  I don't think it's some misuse in Oomph nor that it can be fixed in Oomph...

**Comment by merks** [comment]
Just today I noticed this in the console when I debug launched an installer:
```
Artifact repository out of sync. Overwriting D:\Users\test40\.p2\pool\plugins\jakarta.inject.jakarta.inject-api_2.0.1.jar
Artifact repository out of sync. Overwriting D:\Users\test40\.p2\pool\plugins\org.eclipse.e4.ui.swt.win32_1.2.300.v20240416-0658.jar
Artifact repository out of sync. Overwriting D:\Users\test40\.p2\pool\plugins\org.eclipse.e4.core.di.extensions_0.18.300.v20240413-1529.jar
Artifact repository out of sync. Overwriting D:\Users\test40\.p2\pool\plugins\org.osgi.service.provisioning_1.2.0.201505202024.jar
Artifact repository out of sync. Overwriting D:\Users\test40\.p2\pool\plugins\org.osgi.util.position_1.0.1.201505202026.jar
Artifact repository out of sync. Overwriting D:\Users\test40\.p2\pool\plugins\org.eclipse.equinox.http.service.api_1.2.102.v20250520-0629.jar
```
So this is indeed a case where it doesn't just abort because the descriptor is found,  but it does find a file with the same name already exists.  And this happens in a bundle pool that is not old and is only used for testing.
