### ISSUE TITLE
Problem with Installer Build 329 Version 1.31.0

### ISSUE THREAD

**Issue by lezamad** [eclipse-oomph/oomph#66]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.31.0+Build+329).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```
[2024-02-12 09:36:27] Executing bootstrap tasks
[2024-02-12 09:36:27] OpenJDK Runtime Environment 17.0.9+9
[2024-02-12 09:36:27] Product org.eclipse.products.epp.package.jee.2023-12
[2024-02-12 09:36:27] Bundle org.eclipse.oomph.setup 1.28.0.v20231119-1528, build=329, branch=ce29403a7d4aa58696a4ca86279095fb306631c6
[2024-02-12 09:36:27] Bundle org.eclipse.oomph.setup.core 1.29.0.v20231119-1541, build=329, branch=ce29403a7d4aa58696a4ca86279095fb306631c6
[2024-02-12 09:36:27] Bundle org.eclipse.oomph.setup.p2 1.20.0.v20230617-1322, build=329, branch=ce29403a7d4aa58696a4ca86279095fb306631c6
[2024-02-12 09:36:28] Performing P2 Director (Eclipse IDE for Enterprise Java and Web Developers (2023-12) + JRE 17.0.10)
[2024-02-12 09:36:28] Offline = false
[2024-02-12 09:36:28] Mirrors = true
[2024-02-12 09:36:28] Resolving 93 requirements from 4 repositories to D:\Eclipse\jee-2023-122\eclipse
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.justj.openjdk.hotspot.jre.full.feature.group (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux))(&(osgi.arch=aarch64)(osgi.os=macosx))(&(osgi.arch=ppc64le)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=macosx))(&(osgi.arch=x86_64)(osgi.os=win32))))
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:epp.package.jee [4.30.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.30.0,5.0.0)
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.30.0,5.0.0)
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.buildship.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.common.doc.user.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.doc.user.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.designer.core.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.designer.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.doc.user.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.apache.derby.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.hsqldb.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.ibm.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.ingres.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.jdbc.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.jdt.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.msft.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.mysql.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oda.designer.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oda.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oracle.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.postgresql.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sap.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sdk.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sqlite.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sybase.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.intro.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.modelbase.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sdk.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.data.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.ddl.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.ddlgen.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.parsers.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.results.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.schemaobjecteditor.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.sqlbuilder.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqltools.doc.user.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.eclemma.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.epp.mpc.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.bcoview.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jgit.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.common.eclipselink.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.common.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jaxb.eclipselink.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jaxb.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jpa.eclipselink.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jpa.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jsf.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.common.fproj.enablement.jdt.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.enterprise_ui.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.jsf.apache.trinidad.tagsupport.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_adapters.ext.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_adapters.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_ui.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.web_ui.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.webpageeditor.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.axis2tools.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.cxf.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.jaxws.dom.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.jaxws.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.logback.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.pde.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jaxrs.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jpa.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jsf.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.commons.activity.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.egit.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.git.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.github.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.ide.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.jdt.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.jenkins.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.pde.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.reviews.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext_feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tips.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tm.terminal.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.common.fproj.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.server_adapters.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.xsl.feature.feature.group
[2024-02-12 09:36:28] Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
[2024-02-12 09:36:28] Repository https://download.eclipse.org/justj/jres/17/updates/release/latest
[2024-02-12 09:36:28] Repository https://download.eclipse.org/technology/epp/packages/2023-12/202312011200
[2024-02-12 09:36:28] Repository https://download.eclipse.org/releases/2023-12/202312061001
[2024-02-12 09:36:28] Repository https://download.eclipse.org/oomph/updates/milestone/latest
[2024-02-12 09:36:28] ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at https://download.eclipse.org/releases/2023-12/202312061001/content.xml.xz.
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
  at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.executeHandshake(SSLConnectionSocketFactory.java:303)
  at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
  at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:237)
  at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:472)
  at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.upgradeTls(InternalExecRuntime.java:193)
  at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:172)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
  at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
  at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:251)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
  at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
  at java.base/sun.security.validator.Validator.validate(Unknown Source)
  at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
  at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
  at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.executeHandshake(SSLConnectionSocketFactory.java:303)
  at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
  at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:237)
  at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:472)
  at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.upgradeTls(InternalExecRuntime.java:193)
  at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:172)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
  at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
  at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:251)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
  ... 1 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
  at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
  at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
  at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
  at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
  at java.base/sun.security.validator.Validator.validate(Unknown Source)
  at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
  at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
  at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
  at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
  at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.executeHandshake(SSLConnectionSocketFactory.java:303)
  at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
  at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:237)
  at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:472)
  at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.upgradeTls(InternalExecRuntime.java:193)
  at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:172)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
  at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:106)
  at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:251)
  ... 2 more

[2024-02-12 09:36:28]

**Comment by merks** [comment]
Are you inside a corporate firewall?

**Comment by lezamad** [comment]
Yes this was the problem.

Now I solve.

Thanks
