### ISSUE TITLE
Problem with Installer Build 468 Version 1.32.0

### ISSUE THREAD

**Issue by eduardoortizcuba** [eclipse-oomph/oomph#79]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.32.0+Build+468).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...

Use proxy.
```
[2024-04-04 08:57:52] Repository https://download.eclipse.org/releases/2024-03/202403131000
[2024-04-04 08:57:52] Repository https://download.eclipse.org/oomph/updates/milestone/latest
[2024-04-04 08:58:00] ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at https://download.eclipse.org/releases/2024-03/202403131000.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:409)
  at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:388)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:279)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:520)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1775)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:437)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by merks** [comment]
Have you tried to open all these links in a browser?  They all work for me but I wonder if they work for you?

I imagine some type of proxy configuration might be need. Can you tell me something about your network environment.  Is a network proxy involved such that some type of proxy configuration might be needed?  Might the firewall be blocking certain traffic?

If the installer doesn't work in your environment you can always unzip a package downloaded from here instead:

https://www.eclipse.org/downloads/packages/

**Comment by merks** [comment]
I'll interpret lack of response as there being no further need for help.
