### ISSUE TITLE
Problem with Installer Build 520 Version 1.33.0

### ISSUE THREAD

**Issue by Abhaysingh0859** [eclipse-oomph/oomph#84]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.33.0+Build+520).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
```
Log Details...
```

[2024-04-25 12:40:56] Executing bootstrap tasks
[2024-04-25 12:40:56] OpenJDK Runtime Environment 17.0.10+7
[2024-04-25 12:40:56] Product org.eclipse.products.epp.package.jee.2024-03
[2024-04-25 12:40:56] Bundle org.eclipse.oomph.setup 1.29.0.v20240315-0921, build=520, branch=22c170f4743a69f67060b4c8575ecd80cdbbff89
[2024-04-25 12:40:56] Bundle org.eclipse.oomph.setup.core 1.31.0.v20240315-0921, build=520, branch=22c170f4743a69f67060b4c8575ecd80cdbbff89
[2024-04-25 12:40:56] Bundle org.eclipse.oomph.setup.p2 1.20.0.v20230617-1322, build=468, branch=a85e87d0e90de82218812f7820eaf93a6a75d7c2
[2024-04-25 12:40:56] Performing P2 Director (Eclipse IDE for Enterprise Java and Web Developers (2024-03) + JRE 22.0.0)
[2024-04-25 12:40:56] Offline = false
[2024-04-25 12:40:56] Mirrors = true
[2024-04-25 12:40:56] Resolving 94 requirements from 4 repositories to C:\Users\gauta\OneDrive\Desktop\eclipse\configuration\jee-2024-039\eclipse
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.justj.openjdk.hotspot.jre.full.feature.group (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux))(&(osgi.arch=aarch64)(osgi.os=macosx))(&(osgi.arch=ppc64le)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=macosx))(&(osgi.arch=x86_64)(osgi.os=win32))))
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:epp.package.jee [4.31.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.31.0,5.0.0)
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.31.0,5.0.0)
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.buildship.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.common.doc.user.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.doc.user.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.designer.core.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.designer.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.doc.user.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.apache.derby.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.hsqldb.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.ibm.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.ingres.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.jdbc.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.jdt.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.msft.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.mysql.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oda.designer.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oda.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oracle.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.postgresql.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sap.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sdk.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sqlite.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sybase.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.intro.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.modelbase.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sdk.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.data.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.ddl.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.ddlgen.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.parsers.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.results.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.schemaobjecteditor.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.sqlbuilder.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqltools.doc.user.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.eclemma.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.epp.mpc.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.bcoview.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jgit.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.common.eclipselink.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.common.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jaxb.eclipselink.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jaxb.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jpa.eclipselink.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jpa.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jsf.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.common.fproj.enablement.jdt.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.enterprise_ui.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.jsf.apache.trinidad.tagsupport.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_adapters.ext.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_adapters.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_ui.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.web_ui.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.webpageeditor.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.axis2tools.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.cxf.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.jaxws.dom.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.jaxws.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.logback.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.pde.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jaxrs.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jpa.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jsf.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.commons.activity.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.egit.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.git.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.github.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.ide.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.jdt.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.jenkins.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.pde.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.reviews.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tips.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tm.terminal.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.common.fproj.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.server_adapters.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.xsl.feature.feature.group
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext_feature.feature.group (min=0) (max=0) (greedy)
[2024-04-25 12:40:56] Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
[2024-04-25 12:40:56] Repository https://download.eclipse.org/justj/jres/22/updates/release/latest
[2024-04-25 12:40:56] Repository https://download.eclipse.org/technology/epp/packages/2024-03/202403071200
[2024-04-25 12:40:56] Repository https://download.eclipse.org/releases/2024-03/202403131000
[2024-04-25 12:40:56] Repository https://download.eclipse.org/oomph/updates/milestone/latest
[2024-04-25 12:41:20] ERROR: org.eclipse.equinox.p2.metadata.repository code=1002 Unable to read repository at https://download.eclipse.org/oomph/updates/milestone/latest.
java.io.IOException: https://download.eclipse.org/oomph/updates/milestone/latest is not a valid repository location.
  at org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepositoryFactory.load(CompositeMetadataRepositoryFactory.java:114)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:63)
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:791)
  at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:448)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:231)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:520)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1775)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:437)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

[2024-04-25 12:41:20] 
![2024-04-25](https://github.com/eclipse-oomph/oomph/assets/168069260/7c608ec7-1607-4939-89db-fe839e098234)
![2024-04-25](https://github.com/eclipse-oomph/oomph/assets/168069260/f8ab241b-ac5e-45ab-a625-b55c8a5a41da)
![2024-04-25](https://github.com/eclipse-oomph/oomph/assets/168069260/17c4de3d-ac77-4ec2-9728-b89e05208f3b)

**Comment by merks** [comment]
Thank you for sharing the important details.  This appears to be a network problem.  Is the URL https://download.eclipse.org/oomph/updates/milestone/latest/ accessible in your browser like this:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/acc3dd02-adbf-4c8d-ba05-159fb6c6cf2b)

The repository definitely loads (for me):

![image](https://github.com/eclipse-oomph/oomph/assets/208716/c8ec11cc-a052-43f8-99db-1acfea99b64b)

What can you tell me about your network configuration?  I.e., is there a firewall that might be restricting access?

Note that you can download a zip file from here if your network allows that:

- https://www.eclipse.org/downloads/packages/
- https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-03/R/eclipse-jee-2024-03-R-win32-x86_64.zip

Note also though that you will not be able to perform updates or install new software with such an installation because the IDE application uses the same network access infrastructure as is used by the installer application so if the latter doesn't work, the former won't either, but at least you'll have a functional installation.

**Comment by merks** [comment]
I think I can't help further with network problems.
