### ISSUE TITLE
Problem with Installer Build 5278 Version 1.23.0

### ISSUE THREAD

**Issue by ashishpatilcs111** [eclipse-oomph/oomph#9]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.23.0+Build+5278).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...
```

[2023-07-07 14:43:55] Executing bootstrap tasks
[2023-07-07 14:43:55] OpenJDK Runtime Environment 17.0.1+12
[2023-07-07 14:43:55] Product org.eclipse.products.epp.package.jee.2021-12
[2023-07-07 14:43:55] Bundle org.eclipse.oomph.setup 1.22.0.v20211015-0620, build=5278, branch=a397d5c292b0ea2e68079e5b704e713bfeb15d34
[2023-07-07 14:43:55] Bundle org.eclipse.oomph.setup.core 1.22.0.v20211021-1010, build=5278, branch=a397d5c292b0ea2e68079e5b704e713bfeb15d34
[2023-07-07 14:43:55] Bundle org.eclipse.oomph.setup.p2 1.17.0.v20210601-0619, build=5278, branch=a397d5c292b0ea2e68079e5b704e713bfeb15d34
[2023-07-07 14:43:55] Performing P2 Director (Eclipse IDE for Enterprise Java and Web Developers (2021-12) + JRE 17.0.7)
[2023-07-07 14:43:55] Offline = false
[2023-07-07 14:43:55] Mirrors = true
[2023-07-07 14:43:55] Resolving 88 requirements from 4 repositoriesto C:\Users\hp\eclipse\jee-2021-12\eclipse
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.justj.openjdk.hotspot.jre.full.feature.group (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux))(&(osgi.arch=aarch64)(osgi.os=macosx))(&(osgi.arch=x86_64)(osgi.os=linux))(&(osgi.arch=x86_64)(osgi.os=macosx))(&(osgi.arch=x86_64)(osgi.os=win32))))
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:epp.package.jee [4.22.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.22.0,5.0.0)
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.22.0,5.0.0)
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.buildship.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.common.doc.user.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.doc.user.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.designer.core.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.designer.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.connectivity.oda.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.doc.user.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.apache.derby.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.hsqldb.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.ibm.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.ingres.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.jdbc.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.jdt.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.msft.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.mysql.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oda.designer.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oda.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.oracle.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.postgresql.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sap.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sdk.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sqlite.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.enablement.sybase.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.intro.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.modelbase.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sdk.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.data.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.ddl.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.ddlgen.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.parsers.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.results.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.schemaobjecteditor.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqldevtools.sqlbuilder.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.datatools.sqltools.doc.user.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.eclemma.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.egit.mylyn.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.epp.mpc.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jdt.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.common.eclipselink.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.common.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jaxb.eclipselink.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jaxb.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jpa.eclipselink.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jpt.jpa.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jsf.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.common.fproj.enablement.jdt.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.enterprise_ui.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.jsf.apache.trinidad.tagsupport.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_adapters.ext.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_adapters.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.server_ui.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.web_ui.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.webpageeditor.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.axis2tools.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.cxf.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.jaxws.dom.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.jst.ws.jaxws.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.lemminx.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.logback.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.pde.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jaxrs.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jpa.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.m2e.wtp.jsf.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.bugzilla_feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.context_feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.ide_feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.java_feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn.wikitext_feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.mylyn_feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.pde.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tips.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.tm.terminal.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.embedder.node.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wildwebdeveloper.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.common.fproj.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.server_adapters.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.wst.xsl.feature.feature.group
[2023-07-07 14:43:55] Requirement org.eclipse.equinox.p2.iu:org.eclipse.oomph.setup.feature.group
[2023-07-07 14:43:55] Repository https://download.eclipse.org/justj/jres/17/updates/release/latest
[2023-07-07 14:43:55] Repository https://download.eclipse.org/technology/epp/packages/2021-12/202112021200
[2023-07-07 14:43:55] Repository https://download.eclipse.org/releases/2021-12/202112081000
[2023-07-07 14:43:55] Repository https://download.eclipse.org/oomph/updates/milestone/latest
[2023-07-07 14:43:58] Calculating requirements and dependencies.
[2023-07-07 14:43:59] Computing prerequisite plan
[2023-07-07 14:44:08] Collecting 3 artifacts from https://download.eclipse.org/justj/jres/17/updates/release/latest
[2023-07-07 14:44:09] Downloading org.eclipse.justj.openjdk.hotspot.jre.full
[2023-07-07 14:44:09] Downloading org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64
[2023-07-07 14:44:10] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_17.0.7.v20230425-1502.jar from https://ftp.yz.yamagata-u.ac.jp/pub/eclipse/justj/jres/17/updates/release/17.0.7/features/ (23.27kB)
[2023-07-07 14:44:10] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_17.0.7.v20230425-1502.jar from https://ftp.yz.yamagata-u.ac.jp/pub/eclipse//justj/jres/17/updates/release/17.0.7/plugins/ (19.67kB)
[2023-07-07 14:44:10] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_17.0.7.v20230425-1502.jar from https://ftp.yz.yamagata-u.ac.jp/pub/eclipse/justj/jres/17/updates/release/17.0.7/features/ (23.27kB)
[2023-07-07 14:44:10] Fetching org.eclipse.justj.openjdk.hotspot.jre.full_17.0.7.v20230425-1502.jar from https://ftp.yz.yamagata-u.ac.jp/pub/eclipse//justj/jres/17/updates/release/17.0.7/plugins/ (19.67kB)
[2023-07-07 14:44:10] Fetching org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502.jar from https://mirror.kakao.com/eclipse/justj/jres/17/updates/release/17.0.7/plugins/ (112.29MB)
[2023-07-07 14:44:12] Fetching org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502.jar from https://mirror.kakao.com/eclipse/justj/jres/17/updates/release/17.0.7/plugins/
[2023-07-07 14:47:34] Mirrored 1 artifacts from https://mirror.kakao.com/eclipse/justj/jres/17/updates/release/17.0.7/ at 585kb/s
[2023-07-07 14:47:34] Mirrored 1 artifacts from https://ftp.yz.yamagata-u.ac.jp/pub/eclipse/justj/jres/17/updates/release/17.0.7/ at 33kb/s
[2023-07-07 14:47:34] Mirrored 1 artifacts from https://ftp.yz.yamagata-u.ac.jp/pub/eclipse//justj/jres/17/updates/release/17.0.7/ at 27kb/s
[2023-07-07 14:47:34] Collected 3 artifacts for https://download.eclipse.org/justj/jres/17/updates/release/latest in 206.572s
[2023-07-07 14:47:34] Collecting 3 artifacts from https://download.eclipse.org/releases/2021-12/202112081000
[2023-07-07 14:47:36] Downloading org.eclipse.platform_root
[2023-07-07 14:47:36] Downloading org.eclipse.rcp_root
[2023-07-07 14:47:36] Downloading org.eclipse.platform.ide.executable.win32.win32.x86_64
[2023-07-07 14:47:36] Collected 3 artifacts for https://download.eclipse.org/releases/2021-12/202112081000 in 1.342s
[2023-07-07 14:47:36] Collecting 1 artifacts from https://download.eclipse.org/technology/epp/packages/2021-12/202112021200
[2023-07-07 14:47:36] Downloading epp.package.jee.executable.win32.win32.x86_64
[2023-07-07 14:47:36] Collected 1 artifacts for https://download.eclipse.org/technology/epp/packages/2021-12/202112021200 in 0.002s
[2023-07-07 14:47:49] An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
[2023-07-07 14:47:49] ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:291)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:553)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:345)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3851)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3779)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3760)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3638)
  at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1349)
  at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.access$33(SimpleVariablePage.java:1217)
  at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage$20.run(SimpleVariablePage.java:1162)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=C__Users_hp_eclipse_jee-2021-12_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
  ERROR: org.eclipse.equinox.p2.engine code=0 Cannot invoke "org.eclipse.equinox.p2.engine.IProfile.getProperty(String)" because "profile" is null
  java.lang.NullPointerException: Cannot invoke "org.eclipse.equinox.p2.engine.IProfile.getProperty(String)" because "profile" is null
    at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.buildPGPTrustore(CertificateChecker.java:292)
    at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.checkCertificates(CertificateChecker.java:117)
    at org.eclipse.equinox.internal.p2.engine.phases.CertificateChecker.start(CertificateChecker.java:73)
    at org.eclipse.equinox.internal.p2.engine.phases.CheckTrust.completePhase(CheckTrust.java:63)
    at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
    at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
    at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
    at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
    at org.eclipse.equinox.internal.provisional.p2.director.PlanExecutionHelper.executePlan(PlanExecutionHelper.java:46)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:549)
    at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:345)
    at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3851)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3779)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3760)
    at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3638)
    at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.installPerform(SimpleVariablePage.java:1349)
    at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage.access$33(SimpleVariablePage.java:1217)
    at org.eclipse.oomph.setup.internal.installer.SimpleVariablePage$20.run(SimpleVariablePage.java:1162)

[2023-07-07 14:47:49]

**Comment by merks** [comment]
This is quite an old installer and you are trying to install quite an old version of jee. Is there a reason not to use the latest installer to install the latest version on jee?  Note that the latest installer can be used to install older products if you switch to advanced mode via the menu. I can only fix problems that are reproduced with the latest version.

**Comment by merks** [comment]
Given no answers to questions, I'll assume the latest installer works.
